### ISSUE TITLE
Compilation error CUDA 9.0

### ISSUE THREAD

**Issue by coreybaron** [andyschwarzl/gpuNUFFT#61]
Compilation using CUDA 9.0 on Ubuntu 16.04. Fails at 3% with error:
`nvcc fatal   : Unsupported gpu architecture 'compute_20'`
`CMake Error at gpuNUFFT_f_generated_precomp_kernels.cu.o.cmake:207 (message):`
`  Error generating`
`gpuNUFFT/CUDA/build/src/gpu/coarse/CMakeFiles/gpuNUFFT_f.dir/__/./gpuNUFFT_f_generated_precomp_kernels.cu.o`

**Comment by andyschwarzl** [comment]
Thanks for the info. I will update the CMake config during this week.

**Comment by coreybaron** [comment]
Thanks! Also, I noticed that removing the arch compute_20 allows it to compile. I also added compute_60 and _61 because my GPU is compute 6.1, but now I'm getting runtime errors ("Last CUDA error: no error"). That said, I'm not sure if the errors are due to my specific configuration, because I missed something when updating the cmake, or something else.

**Comment by FlorianKnoll** [comment]
Since the question came up, this option can be found/removed from the /gpuNUFFT/CUDA/CMakeLists.txt file in the block where the CUDA_NVCC_FLAGS are set (lines 83 to 89 in the current (Jan 18) version of the file).

**Comment by pierre-weiss** [comment]
Thanks finished figuring out. Sorry for bothering you! I thought that
erasing the question was enough.

2018-01-03 16:16 GMT+01:00 FlorianKnoll <notifications@github.com>:

**Comment by pierre-weiss** [comment]
By the way: gpuNUFFT works like a charm with Ubuntu 17.10 + Cuda 9.0 (but
deleting arch 20 is needed).

Cheers,
Pierre

2018-01-03 16:37 GMT+01:00 Pierre Weiss <pierre.armand.weiss@gmail.com>:

**Comment by FlorianKnoll** [comment]
Great to hear and no worries. I put the info here because I thought somebody else might have the same question.

**Comment by andyschwarzl** [comment]
d0cbef1 should fix compilation for CUDA 9.0.

I've added a CMake option (FERMI_GPU) to add support for old card generations.

**Comment by coreybaron** [comment]
Thanks! Works great now.
