### ISSUE TITLE
cgsense_brain32ch_recon_2D.m demo error

### ISSUE THREAD

**Issue by MattHibert** [andyschwarzl/gpuNUFFT#63]
Hi,
I installed gpuNUFFT today, and while the phantom demo (cgsense_phantom_recon.m) runs successfully, the brain demo (cgsense_brain32ch_recon_2D.m) gives this output:

Generate NUFFT Operator without coil sensitivities
Estimate coil sensitivities.
Generate NUFFT Operator with coil sensitivities
Time adjoint: 0.063022 s
Time forward: 0.061578 s
Error using  .* 
Matrix dimensions must agree.

Error in cg_sense_2d (line 47)
    y = FT'* (data .* sqrt(repmat(col(mask), [1 nc])));

Error in cgsense_brain32ch_recon_2D (line 88)
img_cgsense = cg_sense_2d(rawdata,FT,senseEst,1,alpha,tol,maxitCG,display,useMultiCoil);

Is there a problem with my installation?

Thanks,
Matt

**Comment by FlorianKnoll** [comment]
Hi Matt,

thanks for pointing this out, I just checked in an update, can you test if it works now?

Best wishes, Florian

**Comment by MattHibert** [comment]
Thanks Florian! That demo is working now.

Matt
