### ISSUE TITLE
CMake Error, variables set to NOTFOUND

### ISSUE THREAD

**Issue by fourthtriumvir** [andyschwarzl/gpuNUFFT#69]
When trying to build gpuNUFFT using CUDA 10 and VS 2017, I get errors saying that variables are set to NOTFOUND. Any help would be appreciated. 

Selecting Windows SDK version 10.0.17763.0 to target Windows 6.1.7601.
The C compiler identification is MSVC 19.16.27027.1
The CXX compiler identification is MSVC 19.16.27027.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0 (found version "10.0") 
Could NOT find Matlab (missing: Matlab_MEX_LIBRARY Matlab_MX_LIBRARY Matlab_ENGINE_LIBRARY Matlab_DATAARRAY_LIBRARY) (found version "9.5")
MATLAB Installation found in C:\Program Files\MATLAB\R2018b
Setting MATLAB DEBUG Option to false
Setting DEBUG Option to false
setting NVCC FLAGS to: -arch=sm_30;-gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_50,code=sm_50;-gencode=arch=compute_52,code=sm_52;-gencode=arch=compute_52,code=compute_52
creating lib with name: gpuNUFFT_f
------start creating libraries-------
Coarse GPU GpuNUFFT Library
Atomic GPU GpuNUFFT Library
MEX file
checking MATLAB INC DIR = 
BUILDING FOR 32 bit Windows
Using MATLAB MX LIB: MATLAB_MX_LIBRARY-NOTFOUND
Using MATLAB MEX LIB: MATLAB_MEX_LIBRARY-NOTFOUND
Using MATLAB INC DIR: C:\Program Files\MATLAB\R2018b\extern\include
set Win 32 suffix
Generate precomputation MEX file
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_LIBRARY (ADVANCED)
    linked by target "gpuNUFFT_f" in directory C:/Users/Jackson/Google Drive/Lab/MATLAB_Codes/gpuNUFFT-master/CUDA/src/gpu/coarse
    linked by target "gpuNUFFT_ATM_f" in directory C:/Users/Jackson/Google Drive/Lab/MATLAB_Codes/gpuNUFFT-master/CUDA/src/gpu/atomic
CUDA_cufft_LIBRARY (ADVANCED)
    linked by target "gpuNUFFT_f" in directory C:/Users/Jackson/Google Drive/Lab/MATLAB_Codes/gpuNUFFT-master/CUDA/src/gpu/coarse
    linked by target "gpuNUFFT_ATM_f" in directory C:/Users/Jackson/Google Drive/Lab/MATLAB_Codes/gpuNUFFT-master/CUDA/src/gpu/atomic
MATLAB_MEX_LIBRARY
    linked by target "mex_gpuNUFFT_adj_f" in directory C:/Users/Jackson/Google Drive/Lab/MATLAB_Codes/gpuNUFFT-master/CUDA/src/gpu/matlab
    linked by target "mex_gpuNUFFT_forw_atomic_f" in directory C:/Users/Jackson/Google Drive/Lab/MATLAB_Codes/gpuNUFFT-master/CUDA/src/gpu/matlab
    linked by target "mex_gpuNUFFT_forw_f" in directory C:/Users/Jackson/Google Drive/Lab/MATLAB_Codes/gpuNUFFT-master/CUDA/src/gpu/matlab
    linked by target "mex_gpuNUFFT_adj_atomic_f" in directory C:/Users/Jackson/Google Drive/Lab/MATLAB_Codes/gpuNUFFT-master/CUDA/src/gpu/matlab
    linked by target "mex_gpuNUFFT_precomp_f" in directory C:/Users/Jackson/Google Drive/Lab/MATLAB_Codes/gpuNUFFT-master/CUDA/src/gpu/matlab/precomputation
MATLAB_MX_LIBRARY
    linked by target "mex_gpuNUFFT_adj_f" in directory C:/Users/Jackson/Google Drive/Lab/MATLAB_Codes/gpuNUFFT-master/CUDA/src/gpu/matlab
    linked by target "mex_gpuNUFFT_forw_atomic_f" in directory C:/Users/Jackson/Google Drive/Lab/MATLAB_Codes/gpuNUFFT-master/CUDA/src/gpu/matlab
    linked by target "mex_gpuNUFFT_forw_f" in directory C:/Users/Jackson/Google Drive/Lab/MATLAB_Codes/gpuNUFFT-master/CUDA/src/gpu/matlab
    linked by target "mex_gpuNUFFT_adj_atomic_f" in directory C:/Users/Jackson/Google Drive/Lab/MATLAB_Codes/gpuNUFFT-master/CUDA/src/gpu/matlab
    linked by target "mex_gpuNUFFT_precomp_f" in directory C:/Users/Jackson/Google Drive/Lab/MATLAB_Codes/gpuNUFFT-master/CUDA/src/gpu/matlab/precomputation

Configuring incomplete, errors occurred!
See also "C:/Users/Jackson/Google Drive/Lab/MATLAB_Codes/gpuNUFFT-master/CUDA/build/CMakeFiles/CMakeOutput.log".

**Comment by andyschwarzl** [comment]
Hi,

the log shows that you are trying to build for 32bit windows. Is that correct? I suppose you need to select to compile for 64bit Windows. 

HTH

**Comment by kennykykyky** [comment]
Hi, do you solve the problem since I have the same question. Thanks!

**Comment by jacksonhair** [comment]
> Hi, do you solve the problem since I have the same question. Thanks!

Andy's suggestion was correct, I needed to compile for 64 bit instead. I do remember encountering some other problem after this, which I ended up solving by just moving to a virtual Linux environment. I can't remember if that problem was related to this one or if it was something else since it has been a while since I performed the installation.

**Comment by kennykykyky** [comment]
Hi, thanks for your email. I have solved the problem by choosing 64 bit for
compilation.
