### ISSUE TITLE
Installation in Windows 11 / Matlab 2021

### ISSUE THREAD

**Issue by athertya** [andyschwarzl/gpuNUFFT#98]
Hi,
I'm trying to install gpuNUFFT in windows 11, using CMake 3.23.2 and VS 17 - 2022. I don't see the build-sln files at all. Can you please address this issue?
![1](https://user-images.githubusercontent.com/82842146/180062836-2fdde723-eb1d-42a2-a4fd-540ebd429993.png)
![2](https://user-images.githubusercontent.com/82842146/180062849-06c5df11-2f3d-498d-88e2-39d74d617913.png)

Thanks,
Jiyo

**Comment by athertya** [comment]
When I tried the generate in cmake - I obtained .sln files , but failed at Visual studio build. Please find my output and error.
![3](https://user-images.githubusercontent.com/82842146/180064806-bbede1c9-9f72-4913-95d6-2e89cd30839f.png)
![4](https://user-images.githubusercontent.com/82842146/180064811-081f5385-0536-46cc-9147-113d848cad75.png)

Any insight will be much appreciated!

**Comment by chaithyagr** [comment]
Hey @athertya , I have not used the windows version,
But as far as I am aware, only visual studio creates the sln files and not cmake-gui.
I can see the error under code `C1189` that you have a version mismatch issue. 
Maybe change the version of visual studio as specified, or add the argument as asked to prevent the check for version as asked (`-allow-unsupported-compiler`) in the CUDA/CMakeLists.txt file for the NVCC flags

**Comment by athertya** [comment]
Hello Chaithya,
I added the argument for NVCC flags. I was able to build successfully. However, the "build" says 6 succeeded, rather than 9, as shown in the video?
I was able to run the matlab code using "useGPU=true", but not when the flag is false. Is it because the build was successful only for 6 instances?
Thanks for you help again!

Regards,
Jiyo
![1](https://user-images.githubusercontent.com/82842146/180484412-c730e59e-dbe5-41d8-b060-fea413270880.png)

**Comment by chaithyagr** [comment]
That's wonderful!
So you got the GPU version up and running. The CPU version mostly needs additional flags to work right. Do you need it? If not I think the GPU versions are much faster and better anyway.

**Comment by athertya** [comment]
I was missing Fessler's nufft package for CPU. Now it runs completely fine. Huge thanks to you. 
But I'm just worried that the video shows 9 builds as success while I only have 6! hope it doesn't affect my recon.

**Comment by chaithyagr** [comment]
I think some build has redued over time. Dont worry, things are working fine for you right? Also I dont see any build errors and anything missing. Any other feature just needs to be enabled as needed. But for now, I think you are good to go. @athertya / @andyschwarzl we can close this issue now. Please repopen if you still face the issue
